import { RedirectOnAuthExpiration } from "@/components/common/redirect";
import { Toaster } from "@/components/ui/sonner";
import { getCurrentUserId } from "@/modules/auth/presentation/api/current-user";
import { AuthProvider } from "@/modules/auth/presentation/components/auth-context";
import { TopNavigationBar } from "@/modules/shared/presentation/components/top-nav";
import { provideUserServices } from "@/modules/users/users.module";
import { TooltipProvider } from "@radix-ui/react-tooltip";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import { LoaderProvider } from "./loader.context";
import { I18nProvider } from "@/components/common/i18n";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerStore = await headers();
  const userId = await getCurrentUserId(headerStore);
  const userService = provideUserServices();
  const user = userId ? await userService.getUserById(userId) : undefined;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-0 overflow-hidden h-screen flex flex-col`}
      >
        <AuthProvider initialUser={user}>
          <I18nProvider language="vi">
            <LoaderProvider>
              <RedirectOnAuthExpiration />
              <TopNavigationBar />
              <TooltipProvider>{children}</TooltipProvider>
              <Toaster />
            </LoaderProvider>
          </I18nProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
