import { RedirectOnAuthExpiration } from "@/components/common/redirect";
import { Toaster } from "@/components/ui/sonner";
import { AuthProvider } from "@/modules/auth/presentation/components/auth-context";
import { getCurrentUser } from "@/modules/auth/presentation/contracts/current-user";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense, use } from "react";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = use(getCurrentUser());

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-0 overflow-hidden`}
      >
        <Suspense fallback={<p>Loading...</p>}>
          <AuthProvider initialUser={user}>
            <RedirectOnAuthExpiration />
            {children}
            <Toaster />
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
