import { RedirectOnAuthExpiration } from "@/components/common/redirect";
import { Toaster } from "@/components/ui/sonner";
import { FullScreenLoader } from "@/components/ui/spinner";
import { getCurrentUserId } from "@/modules/auth/presentation/api/current-user";
import { AuthProvider } from "@/modules/auth/presentation/components/auth-context";
import { provideUserServices } from "@/modules/users/users.module";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Suspense, use } from "react";
import "./globals.css";
import { FullScreenLoaderProvider } from "./loader-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = use(getCurrentUserId());
  const userService = provideUserServices();
  const user = userId ? use(userService.getUserById(userId)) : undefined;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased p-0 overflow-hidden`}
      >
        <Suspense fallback={<FullScreenLoader />}>
          <AuthProvider initialUser={user}>
            <FullScreenLoaderProvider>
              <RedirectOnAuthExpiration />
              {children}
              <Toaster />
            </FullScreenLoaderProvider>
          </AuthProvider>
        </Suspense>
      </body>
    </html>
  );
}
