import { AccountDetailedDto } from "./dtos.types";

export const sampleAccounts = [
  {
    id: "acc_001",
    type: "cash",
    name: "Wallet",
    displayName: "Wallet",
    owner: {
      userId: "user_123",
      email: "john.d@gmail.com",
      firstName: "John",
      lastName: "Doe",
    },
    createdAt: "2025-05-13T12:00:00.000Z",
  } as AccountDetailedDto,
  {
    id: "acc_002",
    type: "debit",
    name: "My Debit Card",
    displayName: "My Debit Card Vietcombank (**** 5678)",
    bankName: "Vietcombank",
    last4: "5678",
    owner: {
      userId: "user_123",
      email: "john.d@gmail.com",
      firstName: "John",
      lastName: "Doe",
    },
    createdAt: "2025-05-12T09:45:00.000Z",
  } as AccountDetailedDto,
  {
    id: "acc_003",
    type: "credit",
    name: "Visa Platinum",
    displayName: "Visa Platinum Techcombank (**** 9876)",
    bankName: "Techcombank",
    last4: "9876",
    statementDay: 12,
    gracePeriodInDays: 45,
    expiration: "2029-05",
    limit: 20000000,
    remainingLimit: 8000000,
    owner: {
      userId: "user_123",
      email: "john.d@gmail.com",
      firstName: "John",
      lastName: "Doe",
    },
    createdAt: "2025-05-10T15:30:00.000Z",
  } as AccountDetailedDto,
  {
    id: "acc_004",
    type: "loan",
    name: "Home Loan",
    displayName: "Home Loan TPBank",
    bankName: "TPBank",
    loanStartDate: "2024-01-01",
    loanEndDate: "2034-01-01",
    originalAmount: 1500000000,
    owner: {
      userId: "user_123",
      email: "john.d@gmail.com",
      firstName: "John",
      lastName: "Doe",
    },
    createdAt: "2024-01-02T08:00:00.000Z",
  } as AccountDetailedDto,
];
